### ISSUE TITLE
Create ElasticSearch index failing

### ISSUE THREAD

**Issue by sean-ocall** [METASPACE2020/sm-engine-ansible#11]
Hi guys,

At the "TASK [sm_webapp : Create ElasticSearch index for the SM web app]" I get a fatal error,
error message is:

fatal: [sm-vbox]: FAILED! => {"changed": true, "cmd": "source /opt/dev/miniconda/bin/activate sm && python scripts/create_es_index.py --drop", "delta": "0:00:00.721794", "end": "2016-07-20 07:02:05.333178", "failed": true, "rc": 1, "start": "2016-07-20 07:02:04.611384", "stderr": "discarding /opt/dev/miniconda/bin from PATH\nprepending /opt/dev/miniconda/envs/sm/bin to PATH\nTraceback (most recent call last):\n  File \"scripts/create_es_index.py\", line 5, in <module>\n    from sm.engine.es_export import ESExporter\n  File \"/opt/dev/miniconda/envs/sm/lib/python2.7/site-packages/sm/engine/es_export.py\", line 1, in <module>\n    from elasticsearch import Elasticsearch\nImportError: No module named elasticsearch", "stdout": "", "stdout_lines": [], "warnings": []}

Thanks, 
Sean

**Comment by intsco** [comment]
Hi Sean,

It seems that elasticsearch package hasn't been installed.
Did you see any other errors before this step?

BR,
Vitaly

**Comment by sean-ocall** [comment]
No that's the only error I can see

**Comment by intsco** [comment]
The full output from ansible would be helpful in this case

**Comment by sean-ocall** [comment]
In Australia so will paste it when I'm back at work in the morning. Thanks guys

**Comment by sean-ocall** [comment]
[ansible_output.txt](https://github.com/SpatialMetabolomics/sm-engine-ansible/files/374996/ansible_output.txt)

**Comment by intsco** [comment]
Hi Sean,

It seems that it is a problem of the version of the SM engine you are trying to install which is not yet supported by the automatic installation.

Try to use a previous version, e.g. v0.3.2, just by putting
sm_branch: v0.3.2
into group_vars/all.yml

Vitaly

**Comment by sean-ocall** [comment]
Have tried 3.0.1 and 3.0.2 and getting the same error. Any other ideas?

ansible output here:
[ansible_output_2.txt](https://github.com/SpatialMetabolomics/sm-engine-ansible/files/377288/ansible_output_2.txt)

**Comment by intsco** [comment]
Hi Sean,

Please use v0.4 branch of sm-engine-ansible. It was made compatible with v0.4 of the SM engine.
git clone https://github.com/intsco/sm-engine-ansible.git
cd sm-engine-ansible
git checkout v0.4

Let me know if you have any other issues.

Best,
Vitaly

**Comment by sean-ocall** [comment]
Just got back to this, all working thanks. Just another issue when I try to run the script which I will report as a new issue
