### ISSUE TITLE
Replace ElasticIPs by service discovery tools

### ISSUE THREAD

**Issue by sfrehse** [METASPACE2020/sm-engine-ansible#13]
Hi,

allocating four ElasticIPs before provisioning not very comfortable. Either they are created while provisioning the EC2 instances or replacing the fixed IPs by service discovery services. As far as I understand the sm-engine-ansible architecture, the fixed IPs are used to discovery the respective services.

Just to name a few tools to solve the service discovery problems: Consul, Zookeeper, etcd.... Moreover, this may enable to run certain services on the same machine discoverable by the service discovery tools.

This reduces cost even more. :-)

Stefan

**Comment by sfrehse** [comment]
As far as I understand that is not required anymore from release rel-v0.5?

**Comment by intsco** [comment]
Hi Stefan,

Thanks for joining in.

Yes, but allocating of elastic IPs is still needed for two instances (sm web server and sm spark master).
They are binded to DNS names later.
If you see any way how Consul or etcd can help, please tell us.

Vitaly
