### ISSUE TITLE
ansible fails at create sm postgres user

### ISSUE THREAD

**Issue by sean-ocall** [METASPACE2020/sm-engine-ansible#14]
Hi, getting this error after the "ansible-playbook provision.yml" command:

TASK [sm_api : Create sm postgres user] ****************************************
fatal: [sm-vbox]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: unknown user: postgres\nsudo: unable to initialize policy plugin\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

I've tried logging into the virtual machine and setting up postgres manually but that just ends up causing other issues down the line. I'm sure this is something simple - can you look into it?

Thanks,
Sean

**Comment by intsco** [comment]
Hi Sean,

Sorry for the late reply. So far, I couldn't quickly fix it.
I will take a closer look at the issue, but only next week as we have a long weekend coming.

Best,
Vitaly

**Comment by intsco** [comment]
The branch https://github.com/METASPACE2020/sm-engine-ansible/tree/vbox-artem should have this and many other issues related to SM engine installation into Virtual Box fixed.
