### ISSUE TITLE
pika connection error on test_runner.py

### ISSUE THREAD

**Issue by sean-ocall** [METASPACE2020/sm-engine-ansible#15]
I never got to try out the vbox-artem solution from a few weeks back - the py3 sm-engine commit seems to have gone missing. Trying again to install from master here (also tried just about every other commit). This time to get through ansible-playbook provision and deploy I had to do a few things:

1. Download and provide mol-images-hmdb.tar.xz locally - otherwise ansible tried to grab it from a local directory which doesn't exist (a mashup of a home directory and a web address).

2. remove all references to: 

```
register: git_deploy
 until: git_deploy | succeeded
```

from deploy_tasks/*.yml files, otherwise I would get: `fatal: [web-1]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'git_deploy | succeeded' failed. The error was: ERROR! template error while templating string: no filter named 'succeeded'"}`

3. On logging into the virtual machine and trying to run test_runner.py, I had to pip install elasticsearch_dsl and pysparkling to get it to run.

4. Finally the test_runner script errors out with the attached error message. 
[vbox-error.txt](https://github.com/METASPACE2020/sm-engine-ansible/files/1168981/vbox-error.txt)

Can you guys point me to a commit that I can just plug and play? What should I point the all.yml file to instead of the py3 sm-engine commit to get vbox-artem working? 

Thanks, Sean

**Comment by intsco** [comment]
Hi Sean,

I checked out rel-v0.7 branch (our next release branch) and followed the instructions from [here](https://github.com/METASPACE2020/sm-engine-ansible/tree/rel-v0.7#setting-up-single-instance-sm-engine-in-virtual-box)

And it seemed to work just fine. At least, I managed to get to the running tests step and run unit tests with
scripts/run.sh test_runner.py -u

BTW, you can send me an email directly once you need some guidance or a small tip.

Best,
Vitaly

**Comment by sean-ocall** [comment]
Thanks Vitaly,

Please close the issue if you think it's not a bug - I'm just going to install sm-engine directly for now. Will check back with the ansible version some time in the future.
