### ISSUE TITLE
roles and ssh issues

### ISSUE THREAD

**Issue by sean-ocall** [METASPACE2020/sm-engine-ansible#2]
Installing on Red Hat EL7. When I run vagrant I have to copy 'common' from the 'roles' folder to the 'vbox' folder for it to run through. 

When I then run the ansible command, it again complains about missing roles, so if I copy the remaining folders over from 'roles', I can get through to an error due to a missing 'sm' role. I've tried using each of the sm_\* folders as the 'sm' role but end up with a connection error: 

<i>"fatal: [sm-vbox]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true} </i>

The process hasn't added any id_rsa or is_rsa.pub into my .ssh directories.

Can you point to where I'm going wrong? I have previously installed SM_distributed via pip etc, but would like to get this new install pipeline up and running. 

Thanks,
Sean

**Comment by lomereiter** [comment]
Hi,
It seems you need to generate a public key.
Please run `ssh-keygen -t rsa` to create one.

**Comment by intsco** [comment]
Hi Sean,

Thanks for your interest. Virtual Box installation seems to be a bit scrambled after the latest ansible roles update. I will test it today and get back to you once I am sure everything works again.

Thanks,
Vitaly

**Comment by intsco** [comment]
Hi Sean,

I updated the roles, plays and README. Now everything should just work.

Best regards,
Vitaly

**Comment by sean-ocall** [comment]
All good - I have found another small isue, but this one is done. Many thanks, Sean
