### ISSUE TITLE
ansible git clone of sm, and spark key pair generation failing

### ISSUE THREAD

**Issue by sean-ocall** [METASPACE2020/sm-engine-ansible#3]
It fails at this point: 

<i>TASK [sm_webapp : clone sm git repository] *************************************</i>

with this error: 

<i>
fatal: [sm-vbox]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1465172823.75-50583051330552/git\", line 3009, in <module>\r\n    main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1465172823.75-50583051330552/git\", line 753, in main\r\n    clone(git_path, module, repo, dest, remote, depth, version, bare, reference, refspec, verify_commit)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1465172823.75-50583051330552/git\", line 329, in clone\r\n    if is_remote_branch(git_path, module, dest, repo, version) \\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1465172823.75-50583051330552/git\", line 439, in is_remote_branch\r\n    if version in out:\r\nTypeError: 'in <string>' requires string as left operand, not NoneType\r\n", "msg": "MODULE FAILURE", "parsed": false}
</i>

If I manually clone SM_distributed into /opt/dev/sm and delete the relevant code from the sm_webapp role tasks/main.yml, everything else runs smoothly up to: 

<i>TASK [spark : generate a key pair for remote ubuntu user (locally)] ************</i>

which errors out with: 
<i>
fatal: [sm-vbox -> localhost]: FAILED! => {"changed": true, "cmd": "ssh-keygen -f /home/intsco/.ssh/ubuntu_spark -t rsa -N ''", "delta": "0:00:00.032162", "end": "2016-06-06 11:56:12.548935", "failed": true, "rc": 1, "start": "2016-06-06 11:56:12.516773", "stderr": "open /home/intsco/.ssh/ubuntu_spark failed: No such file or directory.", "stdout": "Generating public/private rsa key pair.\nSaving the key failed: /home/intsco/.ssh/ubuntu_spark.", "stdout_lines": ["Generating public/private rsa key pair.", "Saving the key failed: /home/intsco/.ssh/ubuntu_spark."], "warnings": []}
</i>

Looking on the virtual machine, there is no 'intsco' home directory and no user 'intsco'.

Thanks,
Sean

**Comment by intsco** [comment]
Hi there,

I suspect the reason for failing may be missing parameter sm_branch value.
Did you skip the step "Put the SM engine version of interest into group_vars/all.yml as value for the sm_branch variable"?

Best,
Vitaly

**Comment by sean-ocall** [comment]
Yes, I did forget that, and it has solved the git issue, but the spark key pair generation is still failing. 

Have you hardcoded your own filesystem folder names into this somehow?

**Comment by intsco** [comment]
Hi,

Indeed, spark_key_file default value was wrong. 
Fixed.

Thanks!

**Comment by sean-ocall** [comment]
Everything working now, all tests passed, example job didn't finish though so I will start a new issue. Thanks!
