### ISSUE TITLE
missing sm.yml 

### ISSUE THREAD

**Issue by frulo** [METASPACE2020/sm-engine-ansible#4]
Hello, 

after the SM_distributed installation is know working well, I'm now trying to use this more comfortable installation. 

on the step `ansible-playbook sm.yml` I get this error `ERROR! the playbook: sm.yml could not be found`. 

kind regards,

Orlando

**Comment by intsco** [comment]
Hello Orlando,

Thank you for the feedback.
The command was misspelled.
Correct one is ansible-playbook provision.yml

Best,
Vitaly

**Comment by frulo** [comment]
Hello Vitaly,

now I get the following error:

`
TASK [sm_spark_master : Install SM into conda environment] *********************
changed: [sm-vbox]

TASK [sm_spark_master : Put activate_conda_env.sh scripts to] ******************
fatal: [sm-vbox]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'aws_access_key_id' is undefined"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @provision.retry

PLAY RECAP *********************************************************************
sm-vbox                    : ok=76   changed=49   unreachable=0    failed=1  
`

and if I run the tests (`scripts/run.sh test_runner.py -u -r`) I get the following error:
`____________________________________________________________________________ ERROR collecting sm/engine/tests/test_formulas.py _____________________________________________________________________________
sm/engine/tests/test_formulas.py:7: in <module>
    from sm.engine.tests.util import ds_config
sm/engine/tests/util.py:4: in <module>
    from pyspark import SparkContext, SparkConf
E   ImportError: No module named pyspark
`

Best,
Orlando

**Comment by intsco** [comment]
Hello Orlando,

As a workaround try to put random values for parameters  in group_vars/all.yml
aws_access_key_id, aws_secret_access_key.

I'm sorry but I have no access to a laptop for fixing bugs till 27th June.

Thanks

Best,
Vitaly

**Comment by frulo** [comment]
Thank you, it works...

**Comment by frulo** [comment]
To be able to run the test Dataset I have to increase the memory of the virtual machine to 8192Mb. Maybe it would be helpful to also increase it on the  vagrant file.

Best

Orlando

**Comment by intsco** [comment]
Hi Orlando,

On my machine I used virtual machines with 4096Mb of memory and it worked.
Can you recall the issues that you had with 4Gb memory only?

Best,
Vitaly

**Comment by frulo** [comment]
With only 4GB memory I could not run the molecule annotation job... With 8GB it works...

**Comment by intsco** [comment]
Hi Orlando,

https://github.com/SpatialMetabolomics/sm-engine-ansible/commit/664ae20607d21c99a833b387280432e24eb9270a should solve it without increasing VM's memory.

Regards,
Vitaly

**Comment by frulo** [comment]
Hi
with this commit I get no errors in the molecule annotation job. But I also can't see any results in the web app (List is empty). Only if I increase the Memory to 8GB I can see the results after running the molecule annotation job in the web app.
