### ISSUE TITLE
aws installation

### ISSUE THREAD

**Issue by frulo** [METASPACE2020/sm-engine-ansible#5]
Hello, 

now I tried the aws installation and get the following error: 

`"Traceback (most recent call last):\n  File \"manage_instances.py\", line 183, in <module>\n    'sm web app', 'sm_webserver_aws', webserver_block_dev_maps)\n  File \"manage_instances.py\", line 143, in start_instances\n    launch_inst(inst_name, inst_type, spot_price, new_inst_n, el_ip_id, sec_group, host_group, block_dev_maps)\n  File \"manage_instances.py\", line 74, in launch_inst\n    BlockDeviceMappings=block_dev_maps\n  File \"/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py\", line 518, in do_action\n    response = action(self, *args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/boto3/resources/action.py\", line 83, in __call__\n    response = getattr(parent.meta.client, operation_name)(**params)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/client.py\", line 262, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/client.py\", line 552, in _make_api_call\n    raise ClientError(parsed_response, operation_name)\nbotocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the RunInstances operation: Value () for parameter groupId is invalid. The value cannot be empty", "stdout": "Start 1 instance(s) of type c4.large, name=sm-dev-webserver\nLaunching 1 new instances..."`

I think that the SecurityGroups 'sm web app' was not generated... If I set this to 'default' I get the following error:
`"Traceback (most recent call last):\n  File \"manage_instances.py\", line 183, in <module>\n    'default', 'sm_webserver_aws', webserver_block_dev_maps)\n  File \"manage_instances.py\", line 143, in start_instances\n    launch_inst(inst_name, inst_type, spot_price, new_inst_n, el_ip_id, sec_group, host_group, block_dev_maps)\n  File \"manage_instances.py\", line 74, in launch_inst\n    BlockDeviceMappings=block_dev_maps\n  File \"/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py\", line 518, in do_action\n    response = action(self, *args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/boto3/resources/action.py\", line 83, in __call__\n    response = getattr(parent.meta.client, operation_name)(**params)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/client.py\", line 262, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/client.py\", line 552, in _make_api_call\n    raise ClientError(parsed_response, operation_name)\nbotocore.exceptions.ClientError: An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id '[ami-f9a62c8a]' does not exist"`

Best,

Orlando

**Comment by intsco** [comment]
Hi Orlando,

I'm sorry for the late answer. I've been on vacation for the last two weeks.

Actually you are the first outside user who decided to test the AWS SM engine installation.
I think we will need to go over some set of issues to make it working. But if you have time and desire we can give it a try.

Regarding the image id error message I suppose it caused by ami-f9a62c8a being available only in eu-west-1 AWS region (Ireland).

As for the missing security group you should create a new group with the following inbound rules:
![image](https://cloud.githubusercontent.com/assets/1176502/16374807/7e591780-3c58-11e6-9b0c-ae657fd0b131.png)

Regards,
Vitaly

**Comment by frulo** [comment]
Hi Vitaly

last week I've been on vacation ;)

I have to use a different region because our eu-west-1 do not have a default VPC. Could it not possible to choose the VPC? Maybe there is different Service running at this region...

Should we not create the security group with a script, to avoid manual steps?

Regards,

Orlando

**Comment by intsco** [comment]
Hi Orlando,

For the AWS installation we still have a number of manual steps to complete before you can run ansible scripts for provisioning and setup.
At the moment we do not have plans to make it completely automated as it too time consuming.
But we can get back to it once we see a big demand for it.

Cheers,
Vitaly

**Comment by frulo** [comment]
Hi Vitaly,

is it possible to user a none default VPC? Actually we have no default VPC at eu-west-1 and therefore I can't install the SM-Engine on AWS.

Regards,

Orlando

**Comment by intsco** [comment]
Hi Orlando,

To be honest I haven't testing it with different VPCs but I don't see any problems to use a non default one.

Best,
Vitaly
