### ISSUE TITLE
PostgreSQL port is open to the world

### ISSUE THREAD

**Issue by sfrehse** [METASPACE2020/sm-engine-ansible#6]
Hi, 

in the current AWS deployment, the PostgreSQL port is open to world. In our setting that is generally not applicable due to security constraints. Is that required in your setting or just for debugging purpose?

Stefan

**Comment by intsco** [comment]
Hi Stefan,

For the SM engine only access from the Spark master machine to the Postgres (web app) machine is required.
You can restrict open ports in settings of the security group that you use for the web app instance.

Cheers,
Vitaly
