### ISSUE TITLE
AWS: Error in the provisioning process

### ISSUE THREAD

**Issue by frulo** [METASPACE2020/sm-engine-ansible#7]
Hi,

for both provision steps I get the error

 [WARNING]: Host file not found: ec2.py

 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [SM spark slave instances configuration] **********************************
skipping: no hosts matched

PLAY [SM spark master instance configuration] **********************************
skipping: no hosts matched

PLAY RECAP *********************************************************************

By the way: there is a typo in the filename aws_provision_websever.yml it should be aws_provision_webserver.yml

Orlando

**Comment by intsco** [comment]
Hi,
Addressed by d0fa7d61ca03891022a98b1f9574355f0841a572

Vitaly
