### ISSUE TITLE
hard coded Elastic IP id

### ISSUE THREAD

**Issue by frulo** [METASPACE2020/sm-engine-ansible#8]
Hi,
in the manage_instances.py the elastic-ip-id is hard coded (eipalloc-0c08df69). To start the aws device I have to edit this file. I think that it would be better to make the configuration in one file ('all.yml'?)

Orlando

**Comment by intsco** [comment]
Hi,
Should be solved by this commit 5a66061868290f8c730b9b8249d07090852d6c9e

Vitaly

**Comment by frulo** [comment]
I will try it tomorrow
