### ISSUE TITLE
Credetials

### ISSUE THREAD

**Issue by frulo** [METASPACE2020/sm-engine-ansible#9]
Hi,
apparently the aws_start scrip do not use the credentials setting from all.yml. Actually the default aws credetials were used (~/.aws/credentials). The script take also the default defined region (~/.aws/region), but the region should always be eu-west-1.

Orlando

**Comment by intsco** [comment]
Hi,
There are two pairs of credentials that you need.
First pair is used by ansible/python/boto3 to spin up instances on AWS. For this you need to have ~/.aws/credentials file on developer's machine.
Second one is used to make it possible for the SM engine to read/write into S3 buckets. These credentials are taken from group_vars/all.yml

Vitaly

**Comment by frulo** [comment]
Thanks, I thought I only need one. But thas is OK these way, Thanks

**Comment by intsco** [comment]
I think so far there is nothing wrong with using the same credentials but putting them into different places.
